=== mamchayd/mini-projet-XML-Location-de-voiture/dtdclient.dtd
<!-- DTD created at Mon Nov 14 14:50:26 WET 2016 with EditiX XML Editor (http://www.editix.com). Please insert an encoding attribute header for converting any DTD  -->

<!ELEMENT clients (client+)>
<!ELEMENT client (nom,prenom,adresse,codePostal,ville,date_permis_conduire)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT adresse (#PCDATA)>
<!ELEMENT codePostal (#PCDATA)>
<!ELEMENT ville (#PCDATA)>
<!ELEMENT date_permis_conduire (#PCDATA)>
<!ATTLIST client CIN ID #REQUIRED>

=== mamchayd/mini-projet-XML-Location-de-voiture/clients.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New XML document created with EditiX XML Editor (http://www.editix.com) at Mon Nov 14 14:35:01 WET 2016 -->

<!DOCTYPE clients SYSTEM "dtdclient.dtd">

<clients xsi:noNamespaceSchemaLocation="shemaclient.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

	<client CIN="A152368">

		<nom>AGGAGUI</nom>

		<prenom>Yassine</prenom>

		<adresse>adresse1</adresse>

		<ville>Kenitra</ville>
		
		<codePostal>11111</codePostal>

		<date_permis_conduire>08/05/2016</date_permis_conduire>

	</client>

	

	<client CIN="Z126598">

		<nom>AMCHAYD</nom>

		<prenom>Maryame</prenom>

		<adresse>adresse2</adresse>

		<ville>Meknes</ville>
		
		<codePostal>22222</codePostal>

		<date_permis_conduire>01/12/2016</date_permis_conduire>

	</client>


</clients>
